### ISSUE TITLE
TEAM - UPDATE (Join Team Button)

### ISSUE THREAD

**Issue by rtate2** [rtate2/i-got-next-2#15]
# User Story
As a user, I should be able to click a `Join a Team` button that conditionally renders the partial team and gives an option to select my name from a dropdown menu and allows me to click the "Save Team" button to update the team with new data which will update my database and update the Teams page

# Acceptance Criteria
**WHEN** the user clicks the `Join a Team` button
**THEN** "full" team card will appear
**AND** when the user selects his name from the dropdown menu and clicks the Save Team button the team is updated within the database and the new team information appears in my Teams component

# Dev Notes
- In src/helpers/Data/teamData.js create the axios.put call and export it 
  - const joinTeam = (updateTeam) => axios.post(`${baseUrl}/blahblah`, updateTeam);

- In src/pages/Teams/Teams.js on button click create the form to appear and the spots not already filled by a player will have a dropdown menu for the user to select their name

**Back End Notes**
- Write an update SQL method in Visual studio for single team
- Within TeamsController, create a UpdateTeam( ) API to call the updateSingleTeam( ) method, using a put request from DataAccess/TeamRepository.cs
- Create the updateSingleTeam( ) method within the repository using Dapper / the SQL script created
- Link the frontend with the backend and use Axios to acquire the data from the database/backend

**Comment by jameka23** [comment]
@rtate2 maybe have a teams controller instead of game controller?
