### ISSUE TITLE
Setup SQL Server Database

### ISSUE THREAD

**Issue by rtate2** [rtate2/i-got-next-2#6]
# Dev Notes
- Within MS SQL Server, create database called IGotNext2
  - Create Team Table, Player Table, Court Table, and Administrator Table
  - Add the data to each table (see #1 for reference)
  - Be sure to test each script to be sure the data is being stored correctly
  - Connect DB to backend (see #2 for reference)

**Comment by jameka23** [comment]
@rtate2 remember we no longer need to have the TeamPlayer table
