### ISSUE TITLE
Home Component

### ISSUE THREAD

**Issue by rtate2** [rtate2/i-got-next-2#8]
# User Story
As a user when I visit the app I will see a home page component with an H1 tag of 'I Got Next 2.0' and two buttons titled `Join a Team` and `Create a Team`

As an admin, when I visit the app I will see a home page component with an H1 tag of 'I Got Next 2.0', two buttons and an admin portal link - referenced in #5 

# Acceptance Criteria
**WHEN** the user visits the home page
**THEN** an H1 header of 'I Got Next 2.0' will appear on the top of the page
**AND** two buttons will appear which gives the user to either join a team or create a team
**AND** an admin portal link

# Dev Notes
- In src/components/pages/Home/home.js create the standard React setup; export default the component at the bottom of the page.
- Create the `Create a Team` button, which will route to the 'create team' form
  - `<Link className="btn btn-primary" to="/teams/new">Create a Team</Link>`

- Create the `Join a Team` button, which will conditionally render the part of the card where the player can join a team
  - `<Link className="btn btn-secondary" to="/teams">Join a Team</Link>`
- Import { Link } from 'react-router-dom at the top of the file
- Style according to mockup

**Comment by jameka23** [comment]
@rtate2 also the link for the admin portal
